version: "3.8"

services:
  database:
    container_name: database
    networks:
      - appnet
    build:
      context: ./mysql/
    restart: always

  app:
    container_name: app
    networks:
      - appnet
    build:
      context: .
    ports:
    - 8080
    restart: always

networks:
  appnet:
    name: appnet